@extends('layouts.admin')
@section('title','Detail Pesanan - SiTahu')
@section('content')
<div class="hero"><div><h1>Detail Pesanan {{ $pesanan->nomor_invoice }}</h1><p>Kelola status pesanan dan pembayaran.</p></div><div class="hero-actions"><a class="btn btn-secondary" href="{{ route('admin.pesanan.index') }}">Kembali</a></div></div>
<div class="grid g2">
    <div class="card card-pad"><h2>Informasi Pembeli</h2><div class="list"><div class="list-item"><div class="grow"><strong>{{ $pesanan->user?->name ?? '-' }}</strong><span>{{ $pesanan->user?->email }} · {{ $pesanan->user?->telepon }}</span></div></div><div class="list-item"><div class="grow"><strong>Alamat</strong><span>{{ $pesanan->alamatPengiriman?->alamat_lengkap ?? 'Ambil di toko' }}</span></div></div><div class="list-item"><div class="grow"><strong>Metode Penerimaan</strong><span>{{ $statusLabel($pesanan->metode_pengambilan) }}</span></div></div></div></div>
    <div class="card card-pad"><h2>Update Status</h2><form method="POST" action="{{ route('admin.pesanan.status',$pesanan) }}" class="form-grid" data-confirm-title="Ubah Status Pesanan" data-confirm-message="Yakin ingin mengubah status pesanan {{ $pesanan->nomor_invoice }}?" data-confirm-button="Ubah Status">@csrf @method('PATCH')<div class="form-group full"><label>Status Pesanan</label><select class="field" name="status">@foreach(['menunggu_pembayaran','dibayar','diproses','siap_diambil','dalam_pengantaran','selesai','dibatalkan'] as $s)<option value="{{ $s }}" @selected($pesanan->status===$s)>{{ $statusLabel($s) }}</option>@endforeach</select></div><div class="form-group full"><label>Status Pembayaran</label><select class="field" name="status_pembayaran">@foreach(['menunggu_pembayaran','dibayar','gagal','kedaluwarsa','dibatalkan'] as $s)<option value="{{ $s }}" @selected($pesanan->status_pembayaran===$s)>{{ $statusLabel($s) }}</option>@endforeach</select></div><button class="btn btn-primary" type="submit">Simpan Status</button></form></div>
</div>
<div class="card" style="margin-top:16px"><div class="card-head"><div><h2>Item Pesanan</h2><p>Produk yang dipesan pembeli.</p></div></div><div class="table-wrap"><table><thead><tr><th>Produk</th><th>Qty</th><th>Harga</th><th>Subtotal</th></tr></thead><tbody>@foreach($pesanan->item as $item)<tr><td>{{ $item->produk?->nama ?? '-' }}</td><td>{{ $item->jumlah }}</td><td>{{ $rupiah($item->harga_satuan) }}</td><td>{{ $rupiah($item->subtotal) }}</td></tr>@endforeach</tbody></table></div><div class="card-pad" style="display:flex;justify-content:flex-end;gap:36px;flex-wrap:wrap"><div><span class="sub">Subtotal</span><strong>{{ $rupiah($pesanan->subtotal_produk) }}</strong></div><div><span class="sub">Ongkir</span><strong>{{ $rupiah($pesanan->biaya_pengiriman) }}</strong></div><div><span class="sub">Total</span><strong>{{ $rupiah($pesanan->total_bayar) }}</strong></div></div></div>
@endsection
